const actionTypes = {
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  GET_USERS: 'GET_USERS',
  GETTING_USERS: 'GETTING_USERS',
  REGISTERING: 'REGISTERING',
  LOGIN_IN: 'LOGIN_IN',
  GET_TICKETS: 'GET_TICKETS',
  GETTING_TICKETS: 'GETTING_TICKETS',
  CREATE_TICKET: 'CREATE_TICKET',
  CREATING_TICKET: 'CREATING_TICKET',
  DELETE_TICKET: 'DELETE_TICKET',
  DELETING_TICKET: 'DELETING_TICKET',
  UPDATE_TICKET: 'UPDATE_TICKET',
  UPDATING_TICKET: 'UPDATING_TICKET',
  GET_ADMIN_TICKETS: 'GET_ADMIN_TICKETS',
  GET_STUDENT_TICKETS: 'GET_STUDENT_TICKETS',
  AUTH_ERROR: 'AUTH_ERROR',
  TICKET_ERROR: 'TICKET_ERROR',
};

export default actionTypes;
